/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-08 02:52:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_005fbasic_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/teamProject/LINKLOOM/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LinkLoom/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/inc/footer.jsp", Long.valueOf(1712544676647L));
    _jspx_dependants.put("/inc/asset.jsp", Long.valueOf(1712544676644L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1712544676791L));
    _jspx_dependants.put("/inc/header_visit.jsp", Long.valueOf(1712544676653L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>LINKLOOM</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- CSS FILES -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/linkloom/asset/css/main.css\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@500;600;700&family=Open+Sans&display=swap\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/linkloom/asset/css/bootstrap.min.css\" >\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/linkloom/asset/css/bootstrap-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/linkloom/asset/css/linkloom.css\">      \r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"/linkloom/asset/css/templatemo-topic-listing.css\">       -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- JAVASCRIPT FILES -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script>\r\n");
      out.write("<script src=\"/linkloom/asset/js/main.js\"></script>\r\n");
      out.write("<script src=\"/linkloom/asset/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/linkloom/asset/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"/linkloom/asset/js/jquery.sticky.js\"></script>\r\n");
      out.write("<script src=\"/linkloom/asset/js/click-scroll.js\"></script>\r\n");
      out.write("<script src=\"/linkloom/asset/js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- 비회원 전용 템플릿입니다.  -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<main>\r\n");
      out.write("<div id=\"site-header\" class=\"site-header\">\r\n");
      out.write("            <div id=\"sticky-wrapper\" class=\"sticky-wrapper\" style=\"height: 97px;\">\r\n");
      out.write("            <nav class=\"navbar navbar-expand-lg\" style=\"\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"index.html\">\r\n");
      out.write("                        <i class=\"bi-back\"></i>\r\n");
      out.write("                        <span>LINKLOOM</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("\r\n");
      out.write("                    <button class=\"navbar-toggler collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("    \r\n");
      out.write("                    <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("                        <ul class=\"navbar-nav ms-lg-5 me-lg-auto\">\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link click-scroll menu active\" href=\"/linkloom/visit_home.jsp\">HOME</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("    \r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link click-scroll menu active\" href=\"/linkloom/notice_guide/notice.jsp\">NOTICE&amp;GUIDE</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"d-none d-lg-block\">\r\n");
      out.write("                            <button type=\"button\" class=\"logout-btn\" onclick=\"location.href='/linkloom/login.jsp';\">LOGIN</button>\r\n");
      out.write("                            <button type=\"button\" class=\"logout-btn\" onclick=\"location.href='/linkloom/join.jsp';\">JOIN</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>	\r\n");
      out.write("            </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("      </div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- 일반회원가입 페이지입니다. -->\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<footer class=\"site-footer section-padding\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                    <div class=\"col-lg-3 col-12 mb-4 pb-2\">\r\n");
      out.write("                        <a class=\"navbar-brand mb-2\" href=\"#site-header\">\r\n");
      out.write("                            <i class=\"bi-back\"></i>\r\n");
      out.write("                            <span>LINKLOOM</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-lg-3 col-md-4 col-6\">\r\n");
      out.write("                        <h6 class=\"site-footer-title mb-3\">Resources</h6>\r\n");
      out.write("\r\n");
      out.write("                        <ul class=\"site-footer-links\">\r\n");
      out.write("                            <li class=\"site-footer-link-item\">\r\n");
      out.write("                                <a href=\"#site-header\" class=\"site-footer-link\">Home</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("\r\n");
      out.write("                            <li class=\"site-footer-link-item\">\r\n");
      out.write("                                <a href=\"/linkloom/notice_guide/notice.jsp\" class=\"site-footer-link\">Notice</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("\r\n");
      out.write("                            <li class=\"site-footer-link-item\">\r\n");
      out.write("                                <a href=\"/linkloom/notice_guide/guide.jsp\" class=\"site-footer-link\">Guide</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-lg-3 col-md-4 col-6 mb-4 mb-lg-0\">\r\n");
      out.write("                        <h6 class=\"site-footer-title mb-3\">Information</h6>\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"text-white d-flex mb-1\">\r\n");
      out.write("                            <a href=\"\" class=\"site-footer-link\">\r\n");
      out.write("                                02-0000-0000\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </p>\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"text-white d-flex\">\r\n");
      out.write("                            <a href=\"mailto:info@company.com\" class=\"site-footer-link\">\r\n");
      out.write("                                linkloom@gmail.com\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-3 col-md-4 col-6 mb-4 mb-lg-0\">\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"copyright-text \">Copyright © 2048 Topic Listing Center. All rights reserved.\r\n");
      out.write("                        <br><br>Design: <a rel=\"nofollow\" href=\"https://templatemo.com\" target=\"_blank\">TemplateMo</a> Distribution <a href=\"https://themewagon.com\">ThemeWagon</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
